### ISSUE TITLE
"hexo s" 后报错 TypeError: podcast is not a constructor

### ISSUE THREAD

**Issue by Lyunvy** [guiqiqi/chromate#8] opened 2022-01-14 13:46 UTC
在执行`hexo s` 后报错：
```bash
$ hexo s
INFO  Validating config
INFO  Start processing
FATAL {
  err: TypeError: podcast is not a constructor
      at Hexo.<anonymous> (E:\lyunv\myPodcast\themes\chromate\scripts\feed.js:32:18)
      at Hexo.tryCatcher (E:\lyunv\myPodcast\node_modules\bluebird\js\release\util.js:16:23)
      at Hexo.<anonymous> (E:\lyunv\myPodcast\node_modules\bluebird\js\release\method.js:15:34)
      at E:\lyunv\myPodcast\node_modules\hexo\lib\hexo\index.js:400:22
      at tryCatcher (E:\lyunv\myPodcast\node_modules\bluebird\js\release\util.js:16:23)
      at MappingPromiseArray._promiseFulfilled (E:\lyunv\myPodcast\node_modules\bluebird\js\release\map.js:68:38)
      at MappingPromiseArray.PromiseArray._iterate (E:\lyunv\myPodcast\node_modules\bluebird\js\release\promise_array.js:115:31)
      at MappingPromiseArray.init (E:\lyunv\myPodcast\node_modules\bluebird\js\release\promise_array.js:79:10)
      at MappingPromiseArray._asyncInit (E:\lyunv\myPodcast\node_modules\bluebird\js\release\map.js:37:10)
      at _drainQueueStep (E:\lyunv\myPodcast\node_modules\bluebird\js\release\async.js:97:12)
      at _drainQueue (E:\lyunv\myPodcast\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (E:\lyunv\myPodcast\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (E:\lyunv\myPodcast\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (node:internal/timers:464:21)
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html
```

初始化一个 Hexo 目录，下载主题至主题文件夹，配置主题为 chromate，然后执行`hexo s`即出现该报错。

设置`themes\chromate\_config.yml`中
```yml
rss:
  enable: false
```
后则可正常运行，但无 feed 页面。

**Comment by guiqiqi** [comment] 2022-01-14 16:25
Confirming issue.

**Comment by guiqiqi** [comment] 2022-01-14 16:34
Problem cannot be reproduced, try running this for fixing:

```
npm install podcast --save
```

This error may caused by lacking required package: `podcast` (referenced code may cause this exception):
https://github.com/guiqiqi/chromate/blob/f897047b768de09cef73d656fa585af7ab2a4b5e/scripts/feed.js#L13

**Comment by Lyunvy** [comment] 2022-01-14 18:42
执行`npm install podcast --save`后依旧报此错误，
根据 https://stackoverflow.com/a/55318391 此回答修改此句
https://github.com/guiqiqi/chromate/blob/f897047b768de09cef73d656fa585af7ab2a4b5e/scripts/feed.js#L13
为`const podcast = require("podcast").Podcast;`后不再报错
（虽然不知道是啥原理:joy:）

**Comment by guiqiqi** [comment] 2022-01-15 00:43
Thanks for your feedback, I’ll try to check if the dependent has been updated.

**Comment by guiqiqi** [comment] 2022-01-16 12:32
Fixed in https://github.com/guiqiqi/chromate/releases/tag/v0.0.2

**Closed as completed by guiqiqi** 2022-01-16 12:32 UTC
Labels: bug
